// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyKeeper.Transactions.Core.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyKeeper.Transactions.Core.DAL.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    partial class TransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyKeeper.Transactions.Core.Entities.ReceiptInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OcrDataGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OcrValidationResult")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SpreadsheetEnterTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SpreadsheetEntered")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("UploadDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ReceiptInfos");
                });

            modelBuilder.Entity("MoneyKeeper.Transactions.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReceiptInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptInfoId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyKeeper.Transactions.Core.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyKeeper.Transactions.Core.Entities.ReceiptInfo", "ReceiptInfo")
                        .WithOne("Transaction")
                        .HasForeignKey("MoneyKeeper.Transactions.Core.Entities.Transaction", "ReceiptInfoId");

                    b.Navigation("ReceiptInfo");
                });

            modelBuilder.Entity("MoneyKeeper.Transactions.Core.Entities.ReceiptInfo", b =>
                {
                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
