// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyKeeper.Transactions.Core.DAL;

#nullable disable

namespace MoneyKeeper.Transactions.Core.DAL.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    partial class TransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MoneyKeeper.Transactions.Core.Entities.ReceiptInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OcrDataGenerated")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("OcrValidationResult")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("SpreadsheetEntered")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateOnly>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReceiptInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
